as_of_date: '2026-04-24'
count: 100
generated_at: '2026-04-25T18:17:28.089030'
stocks:
- code: 005930
  market: KOSPI
  market_cap: 1283258154456000
  name: 삼성전자
  rank: 1
  sector: 기타
- code: '000660'
  market: KOSPI
  market_cap: 870922290030000
  name: SK하이닉스
  rank: 2
  sector: 기타
- code: 005935
  market: KOSPI
  market_cap: 123324453901100
  name: 삼성전자우
  rank: 3
  sector: 기타
- code: '373220'
  market: KOSPI
  market_cap: 112554000000000
  name: LG에너지솔루션
  rank: 4
  sector: 기타
- code: 005380
  market: KOSPI
  market_cap: 105040733958000
  name: 현대차
  rank: 5
  sector: 기타
- code: '402340'
  market: KOSPI
  market_cap: 95669829850000
  name: SK스퀘어
  rank: 6
  sector: 기타
- code: '034020'
  market: KOSPI
  market_cap: 81415321656600
  name: 두산에너빌리티
  rank: 7
  sector: 기타
- code: '012450'
  market: KOSPI
  market_cap: 75437255663000
  name: 한화에어로스페이스
  rank: 8
  sector: 기타
- code: '207940'
  market: KOSPI
  market_cap: 70732573128000
  name: 삼성바이오로직스
  rank: 9
  sector: 기타
- code: '329180'
  market: KOSPI
  market_cap: 70428981975000
  name: HD현대중공업
  rank: 10
  sector: 기타
- code: '000270'
  market: KOSPI
  market_cap: 59889353893200
  name: 기아
  rank: 11
  sector: 기타
- code: 009150
  market: KOSPI
  market_cap: 58858632448000
  name: 삼성전기
  rank: 12
  sector: 기타
- code: '105560'
  market: KOSPI
  market_cap: 58686661617000
  name: KB금융
  rank: 13
  sector: 기타
- code: '006400'
  market: KOSPI
  market_cap: 51655324730000
  name: 삼성SDI
  rank: 14
  sector: 기타
- code: 028260
  market: KOSPI
  market_cap: 50515637581500
  name: 삼성물산
  rank: 15
  sector: 기타
- code: 032830
  market: KOSPI
  market_cap: 48900000000000
  name: 삼성생명
  rank: 16
  sector: 기타
- code: '055550'
  market: KOSPI
  market_cap: 47465436100000
  name: 신한지주
  rank: 17
  sector: 기타
- code: 068270
  market: KOSPI
  market_cap: 46385096549000
  name: 셀트리온
  rank: 18
  sector: 기타
- code: '267260'
  market: KOSPI
  market_cap: 44986824480000
  name: HD현대일렉트릭
  rank: 19
  sector: 기타
- code: '042660'
  market: KOSPI
  market_cap: 41335166850600
  name: 한화오션
  rank: 20
  sector: 기타
- code: '012330'
  market: KOSPI
  market_cap: 38334516317500
  name: 현대모비스
  rank: 21
  sector: 기타
- code: 006800
  market: KOSPI
  market_cap: 37435024272000
  name: 미래에셋증권
  rank: 22
  sector: 기타
- code: '010130'
  market: KOSPI
  market_cap: 34273415098000
  name: 고려아연
  rank: 23
  sector: 기타
- code: '010120'
  market: KOSPI
  market_cap: 33975000000000
  name: LS ELECTRIC
  rank: 24
  sector: 기타
- code: 086790
  market: KOSPI
  market_cap: 33829543328400
  name: 하나금융지주
  rank: 25
  sector: 기타
- code: 009540
  market: KOSPI
  market_cap: 33688003216000
  name: HD한국조선해양
  rank: 26
  sector: 기타
- code: '035420'
  market: KOSPI
  market_cap: 33566464532000
  name: NAVER
  rank: 27
  sector: 기타
- code: '298040'
  market: KOSPI
  market_cap: 33120794496000
  name: 효성중공업
  rank: 28
  sector: 기타
- code: 005490
  market: KOSPI
  market_cap: 32885233705000
  name: POSCO홀딩스
  rank: 29
  sector: 기타
- code: '010140'
  market: KOSPI
  market_cap: 30272000000000
  name: 삼성중공업
  rank: 30
  sector: 기타
- code: '015760'
  market: KOSPI
  market_cap: 29658740357400
  name: 한국전력
  rank: 31
  sector: 기타
- code: '034730'
  market: KOSPI
  market_cap: 28892327145500
  name: SK
  rank: 32
  sector: 기타
- code: '042700'
  market: KOSPI
  market_cap: 28164755100000
  name: 한미반도체
  rank: 33
  sector: 기타
- code: 051910
  market: KOSPI
  market_cap: 27636902284500
  name: LG화학
  rank: 34
  sector: 기타
- code: '316140'
  market: KOSPI
  market_cap: 25729375016000
  name: 우리금융지주
  rank: 35
  sector: 기타
- code: '064350'
  market: KOSPI
  market_cap: 25430154269000
  name: 현대로템
  rank: 36
  sector: 기타
- code: '000150'
  market: KOSPI
  market_cap: 24954699735000
  name: 두산
  rank: 37
  sector: 기타
- code: '272210'
  market: KOSPI
  market_cap: 24635088325600
  name: 한화시스템
  rank: 38
  sector: 기타
- code: '267250'
  market: KOSPI
  market_cap: 22750008480000
  name: HD현대
  rank: 39
  sector: 기타
- code: 096770
  market: KOSPI
  market_cap: 22467115525200
  name: SK이노베이션
  rank: 40
  sector: 기타
- code: '003670'
  market: KOSPI
  market_cap: 22414447440000
  name: 포스코퓨처엠
  rank: 41
  sector: 기타
- code: 079550
  market: KOSPI
  market_cap: 21758000000000
  name: LIG디펜스앤에어로스페이스
  rank: 42
  sector: 기타
- code: '017670'
  market: KOSPI
  market_cap: 21479005300000
  name: SK텔레콤
  rank: 43
  sector: 기타
- code: '035720'
  market: KOSPI
  market_cap: 21286197809750
  name: 카카오
  rank: 44
  sector: 기타
- code: 086520
  market: KOSDAQ GLOBAL
  market_cap: 21262545403200
  name: 에코프로
  rank: 45
  sector: 중견기업부
- code: '066570'
  market: KOSPI
  market_cap: 20768014342500
  name: LG전자
  rank: 46
  sector: 기타
- code: 000810
  market: KOSPI
  market_cap: 20359247688000
  name: 삼성화재
  rank: 47
  sector: 기타
- code: '247540'
  market: KOSDAQ GLOBAL
  market_cap: 20348730272000
  name: 에코프로비엠
  rank: 48
  sector: 우량기업부
- code: 033780
  market: KOSPI
  market_cap: 20206024849000
  name: KT&G
  rank: 49
  sector: 기타
- code: '011200'
  market: KOSPI
  market_cap: 19902321167000
  name: HMM
  rank: 50
  sector: 기타
- code: '196170'
  market: KOSDAQ GLOBAL
  market_cap: 19753988067000
  name: 알테오젠
  rank: 51
  sector: 우량기업부
- code: '000720'
  market: KOSPI
  market_cap: 19264547345000
  name: 현대건설
  rank: 52
  sector: 기타
- code: '138040'
  market: KOSPI
  market_cap: 19161262758500
  name: 메리츠금융지주
  rank: 53
  sector: 기타
- code: '024110'
  market: KOSPI
  market_cap: 17822468172150
  name: 기업은행
  rank: 54
  sector: 기타
- code: '278470'
  market: KOSPI
  market_cap: 16847169750000
  name: 에이피알
  rank: 55
  sector: 기타
- code: 047810
  market: KOSPI
  market_cap: 16707233339800
  name: 한국항공우주
  rank: 56
  sector: 기타
- code: 086280
  market: KOSPI
  market_cap: 16687500000000
  name: 현대글로비스
  rank: 57
  sector: 기타
- code: '030200'
  market: KOSPI
  market_cap: 15549737964500
  name: KT
  rank: 58
  sector: 기타
- code: '003550'
  market: KOSPI
  market_cap: 14805272160000
  name: LG
  rank: 59
  sector: 기타
- code: '071050'
  market: KOSPI
  market_cap: 14433031928000
  name: 한국금융지주
  rank: 60
  sector: 기타
- code: '047050'
  market: KOSPI
  market_cap: 14302522664400
  name: 포스코인터내셔널
  rank: 61
  sector: 기타
- code: 0126Z0
  market: KOSPI
  market_cap: 14282870126000
  name: 삼성에피스홀딩스
  rank: 62
  sector: 기타
- code: '047040'
  market: KOSPI
  market_cap: 13477770526400
  name: 대우건설
  rank: 63
  sector: 기타
- code: 010950
  market: KOSPI
  market_cap: 13442385364800
  name: S-Oil
  rank: 64
  sector: 기타
- code: 018260
  market: KOSPI
  market_cap: 13138750440000
  name: 삼성에스디에스
  rank: 65
  sector: 기타
- code: '259960'
  market: KOSPI
  market_cap: 13012971979500
  name: 크래프톤
  rank: 66
  sector: 기타
- code: '011070'
  market: KOSPI
  market_cap: 12827571994000
  name: LG이노텍
  rank: 67
  sector: 기타
- code: 005940
  market: KOSPI
  market_cap: 12507687351900
  name: NH투자증권
  rank: 68
  sector: 기타
- code: '006260'
  market: KOSPI
  market_cap: 12433200000000
  name: LS
  rank: 69
  sector: 기타
- code: '323410'
  market: KOSPI
  market_cap: 12071147056100
  name: 카카오뱅크
  rank: 70
  sector: 기타
- code: '277810'
  market: KOSDAQ
  market_cap: 11872713096000
  name: 레인보우로보틱스
  rank: 71
  sector: 기술성장기업부
- code: 039490
  market: KOSPI
  market_cap: 11782157352000
  name: 키움증권
  rank: 72
  sector: 기타
- code: '307950'
  market: KOSPI
  market_cap: 11778600269000
  name: 현대오토에버
  rank: 73
  sector: 기타
- code: 005830
  market: KOSPI
  market_cap: 11462561075000
  name: DB손해보험
  rank: 74
  sector: 기타
- code: '443060'
  market: KOSPI
  market_cap: 11365282110000
  name: HD현대마린솔루션
  rank: 75
  sector: 기타
- code: '007660'
  market: KOSPI
  market_cap: 11260974194600
  name: 이수페타시스
  rank: 76
  sector: 기타
- code: '352820'
  market: KOSPI
  market_cap: 10861766748000
  name: 하이브
  rank: 77
  sector: 기타
- code: 028050
  market: KOSPI
  market_cap: 10290000000000
  name: 삼성E&A
  rank: 78
  sector: 기타
- code: '016360'
  market: KOSPI
  market_cap: 9965880000000
  name: 삼성증권
  rank: 79
  sector: 기타
- code: '003230'
  market: KOSPI
  market_cap: 9905914725000
  name: 삼양식품
  rank: 80
  sector: 기타
- code: '000250'
  market: KOSDAQ
  market_cap: 9652749728000
  name: 삼천당제약
  rank: 81
  sector: 중견기업부
- code: 058470
  market: KOSDAQ GLOBAL
  market_cap: 9480754140000
  name: 리노공업
  rank: 82
  sector: 우량기업부
- code: '267270'
  market: KOSPI
  market_cap: 9340560774600
  name: HD건설기계
  rank: 83
  sector: 기타
- code: 000880
  market: KOSPI
  market_cap: 9243588180900
  name: 한화
  rank: 84
  sector: 기타
- code: 003490
  market: KOSPI
  market_cap: 9150283425850
  name: 대한항공
  rank: 85
  sector: 기타
- code: '298380'
  market: KOSDAQ
  market_cap: 8801229183600
  name: 에이비엘바이오
  rank: 86
  sector: 기술성장기업부
- code: 005387
  market: KOSPI
  market_cap: 8566162850000
  name: 현대차2우B
  rank: 87
  sector: 기타
- code: '950160'
  market: KOSDAQ
  market_cap: 8558341050000
  name: 코오롱티슈진
  rank: 88
  sector: 외국기업(소속부없음)
- code: 009830
  market: KOSPI
  market_cap: 8482896651600
  name: 한화솔루션
  rank: 89
  sector: 기타
- code: 090430
  market: KOSPI
  market_cap: 8417108020100
  name: 아모레퍼시픽
  rank: 90
  sector: 기타
- code: 028300
  market: KOSDAQ
  market_cap: 8014576740800
  name: HLB
  rank: 91
  sector: 중견기업부
- code: '326030'
  market: KOSPI
  market_cap: 8011445475000
  name: SK바이오팜
  rank: 92
  sector: 기타
- code: 066970
  market: KOSPI
  market_cap: 8004529372500
  name: 엘앤에프
  rank: 93
  sector: 기타
- code: '001440'
  market: KOSPI
  market_cap: 7989266805000
  name: 대한전선
  rank: 94
  sector: 기타
- code: '161390'
  market: KOSPI
  market_cap: 7766966826300
  name: 한국타이어앤테크놀로지
  rank: 95
  sector: 기타
- code: '180640'
  market: KOSPI
  market_cap: 7624252261800
  name: 한진칼
  rank: 96
  sector: 기타
- code: '000100'
  market: KOSPI
  market_cap: 7550592574800
  name: 유한양행
  rank: 97
  sector: 기타
- code: '377300'
  market: KOSPI
  market_cap: 7479068795100
  name: 카카오페이
  rank: 98
  sector: 기타
- code: 052690
  market: KOSPI
  market_cap: 7445256000000
  name: 한전기술
  rank: 99
  sector: 기타
- code: '141080'
  market: KOSDAQ GLOBAL
  market_cap: 7322067600000
  name: 리가켐바이오
  rank: 100
  sector: 기술성장기업부
